// <auto-generated />
namespace ProdCientifica.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class act1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(act1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804231400426_act1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
